---
- name: Configure NETCONF
  tags: [api, netconf]
  ios_config:
    provider: "{{provider}}"
    lines:
      - netconf-yang
      - netconf-yang cisco-odm polling-enable
      - restconf
      - ip http server
      - ip http secure-server

- name: Pause for NETCONF to start
  pause:
    seconds: 45
